name: Scrape and Notify

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行
  workflow_dispatch:  # 手動実行

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download previous data
        id: download-artifact
        continue-on-error: true  # アーティファクトがなくても処理を続行
        uses: actions/download-artifact@v4
        with:
          name: previous-data
          path: ./previous-data

      - name: Run script
        run: node index.js
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}

      - name: Upload new data
        uses: actions/upload-artifact@v4
        with:
          name: previous-data
          path: ./previous_data.json
          retention-days: 30 # 30日間保存
